name: com_kbbisuperapp
version: 1.0.1+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  loading_animation_widget: ^1.2.0+2
  http: ^0.13.5
  html: ^0.15.0
  url_launcher: ^6.1.5

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_launcher_icons: ^0.10.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon-apps.png"


flutter: 
  uses-material-design: true
  assets:
    - assets/
